name: Build and push CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: |
          pwd
          ls -l
          npm install
          npm run build
      - name: Clone and update destination repository
        run: |
          pwd
          ls -l
          cd ..
          git clone https://github.com/Healthy-Lifestyle-Assistant/client-build.git
          ls -l
          cp -a client/dist/ client-build/
          cd client-build/
          git add .
          git commit -m "VERSION 0.0.1"
          git push -u origin main
